name: 'Better CODEOWNERS Check'

on:
  pull_request:
    branches:
      - main

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Better CODEOWNERS Check'
        uses: nickzas/better-codeowners@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          post_comment: true
